# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonmd', '0002_freshtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procode',
            name='fstateid',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
