# Generated by Django 2.0.8 on 2018-11-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonmd', '0003_auto_20180522_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveGroup',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fgroupnum', models.CharField(max_length=20, null=True, verbose_name='组号')),
                ('fstime', models.DateField()),
                ('fftime', models.DateTimeField(null=True)),
                ('fntime', models.DateTimeField(null=True)),
                ('fsmail', models.NullBooleanField()),
                ('ffmail', models.BooleanField(default=False)),
                ('ffmemory', models.NullBooleanField()),
                ('fstateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonmd.ProCode')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurveWord',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fnumlimit', models.IntegerField(verbose_name='每组数量')),
                ('fgroupclass', models.CharField(max_length=30, verbose_name='条件标识')),
                ('fstime', models.DateField(verbose_name='开始记忆时间')),
                ('fmail', models.BooleanField(verbose_name='邮件提醒')),
            ],
        ),
    ]
