# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonmd', '0003_auto_20180522_1651'),
        ('dictdata', '0010_remove_jaword_fcreater'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveGroup',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fstime', models.DateTimeField()),
                ('fftime', models.DateTimeField(null=True)),
                ('fntime', models.DateTimeField(null=True)),
                ('fgroupnum', models.IntegerField(verbose_name='组号')),
                ('fsmail', models.NullBooleanField()),
                ('ffmail', models.BooleanField(default=False)),
                ('ffmemory', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CurveWord',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fnumlimit', models.IntegerField(verbose_name='每组数量')),
                ('fgroupclass', models.CharField(max_length=30)),
                ('fstime', models.CharField(max_length=5, null=True, verbose_name='默认开始时间')),
                ('fmail', models.BooleanField(verbose_name='邮件提醒')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encurvew2user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewWord',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fgroupnum', models.IntegerField(null=True, verbose_name='组号')),
                ('flevnum', models.IntegerField()),
                ('fcreatedate', models.DateField(auto_now=True)),
                ('fnewword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enword2new', to='dictdata.EnWord')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newword2user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curvegroup',
            name='fcurveword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enword2curve', to='enstudy.CurveWord'),
        ),
        migrations.AddField(
            model_name='curvegroup',
            name='fstateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enword2procode', to='commonmd.ProCode'),
        ),
        migrations.AddField(
            model_name='curvegroup',
            name='fuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encurveg2user', to=settings.AUTH_USER_MODEL),
        ),
    ]
