# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictdata', '0010_remove_jaword_fcreater'),
    ]

    operations = [
        migrations.CreateModel(
            name='En2Cn',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fuser', models.CharField(blank=True, max_length=30, null=True)),
                ('fdate', models.DateTimeField(auto_now=True)),
                ('fcnword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.CnWord')),
                ('fenword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.EnWord')),
            ],
        ),
        migrations.CreateModel(
            name='Ja2Cn',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fuser', models.CharField(blank=True, max_length=30, null=True)),
                ('fdate', models.DateTimeField(auto_now=True)),
                ('fcnword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.CnWord')),
                ('fjaword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.JaWord')),
            ],
        ),
        migrations.CreateModel(
            name='Ja2En',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fuser', models.CharField(blank=True, max_length=30, null=True)),
                ('fdate', models.DateTimeField(auto_now=True)),
                ('fenword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.EnWord')),
                ('fjaword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.JaWord')),
            ],
        ),
        migrations.RemoveField(
            model_name='lantrans',
            name='fcnword',
        ),
        migrations.RemoveField(
            model_name='lantrans',
            name='fenword',
        ),
        migrations.RemoveField(
            model_name='lantrans',
            name='fjaword',
        ),
        migrations.DeleteModel(
            name='LanTrans',
        ),
    ]
