# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictdata', '0011_auto_20180604_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fminclass', models.CharField(max_length=30)),
                ('fcword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.CnWord')),
            ],
        ),
        migrations.CreateModel(
            name='EnGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fminclass', models.CharField(max_length=30)),
                ('feword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.EnWord')),
            ],
        ),
        migrations.AlterModelTable(
            name='jagroup',
            table=None,
        ),
    ]
