# Generated by Django 2.0.6 on 2018-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictdata', '0012_auto_20180604_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnword',
            name='frelaword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enword',
            name='frelaword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jaword',
            name='frelaword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='en2cn',
            unique_together={('fenword', 'fcnword')},
        ),
        migrations.AlterUniqueTogether(
            name='ja2cn',
            unique_together={('fjaword', 'fcnword')},
        ),
        migrations.AlterUniqueTogether(
            name='ja2en',
            unique_together={('fjaword', 'fenword')},
        ),
    ]
