# Generated by Django 2.0.9 on 2018-11-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictdata', '0013_auto_20180625_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cngroup',
            name='fcword',
        ),
        migrations.RemoveField(
            model_name='engroup',
            name='feword',
        ),
        migrations.RemoveField(
            model_name='jagroup',
            name='fjword',
        ),
        migrations.DeleteModel(
            name='CnGroup',
        ),
        migrations.DeleteModel(
            name='EnGroup',
        ),
        migrations.DeleteModel(
            name='JaGroup',
        ),
    ]
