# Generated by Django 2.0.9 on 2018-11-28 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictdata', '0013_auto_20180625_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CnNewWord',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('flevnum', models.IntegerField(null=True)),
                ('fgroupnum', models.CharField(max_length=20, null=True, verbose_name='组号')),
                ('fcreatedate', models.DateField(auto_now=True)),
                ('fnewword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.CnWord')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnNewWord',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('flevnum', models.IntegerField(null=True)),
                ('fgroupnum', models.CharField(max_length=20, null=True, verbose_name='组号')),
                ('fcreatedate', models.DateField(auto_now=True)),
                ('fnewword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.EnWord')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JpNewWord',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('flevnum', models.IntegerField(null=True)),
                ('fgroupnum', models.CharField(max_length=20, null=True, verbose_name='组号')),
                ('fcreatedate', models.DateField(auto_now=True)),
                ('fnewword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictdata.JaWord')),
                ('fuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
