# Generated by Django 2.0.8 on 2018-10-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jpstudy', '0006_auto_20180530_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curvegroup',
            name='fcurveword',
        ),
        migrations.RemoveField(
            model_name='curveword',
            name='fedate',
        ),
        migrations.RemoveField(
            model_name='curveword',
            name='fsdate',
        ),
        migrations.AddField(
            model_name='newword',
            name='fcurvegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jpstudy.CurveGroup', verbose_name='生词组'),
        ),
        migrations.AddField(
            model_name='newword',
            name='fgroupnum',
            field=models.CharField(max_length=20, null=True, verbose_name='组号'),
        ),
        migrations.AlterField(
            model_name='curvegroup',
            name='fgroupnum',
            field=models.CharField(max_length=20, null=True, verbose_name='组号'),
        ),
        migrations.AlterField(
            model_name='curveword',
            name='fgroupclass',
            field=models.CharField(max_length=30, verbose_name='生词组号'),
        ),
        migrations.AlterField(
            model_name='newword',
            name='flevnum',
            field=models.IntegerField(null=True),
        ),
    ]
