# Generated by Django 2.0.8 on 2018-11-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictdata', '0013_auto_20180625_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonmd', '0004_curvegroup_curveword'),
        ('jpstudy', '0007_auto_20181009_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewWord',
            new_name='JpNewWord',
        ),
        migrations.RemoveField(
            model_name='curvegroup',
            name='fstateid',
        ),
        migrations.RemoveField(
            model_name='curvegroup',
            name='fuser',
        ),
        migrations.RemoveField(
            model_name='curveword',
            name='fuser',
        ),
        migrations.AlterField(
            model_name='jpnewword',
            name='fcurvegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commonmd.CurveGroup', verbose_name='生词组'),
        ),
        migrations.DeleteModel(
            name='CurveGroup',
        ),
        migrations.DeleteModel(
            name='CurveWord',
        ),
    ]
